**Logistic regression**

In [2]:
import os
# Limit OS-level process affinity to exclusively use Core 0.
# This strictly physically constraints Polars, PyTorch, and everything else in this notebook to 1 core.
#os.sched_setaffinity(0, {0,1})

# Also keep your GPU and general thread limits just in case
os.environ["CUDA_VISIBLE_DEVICES"] = "0" 
#os.environ["OMP_NUM_THREADS"] = "2"
#os.environ["POLARS_MAX_THREADS"] = "2" # Must be set before 'import polars'

In [2]:
import polars as pl
import importlib
import lr_rf_cuml_based
from datetime import date, datetime
import json

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)

In [2]:
importlib.reload(lr_rf_cuml_based)
from lr_rf_cuml_based import mach_lern
import polars as pl

In [3]:
df_aapl = pl.scan_csv('/mnt/windows/windows_hanka_bcthesis/full_stock_prices/AAPL.csv').with_columns(pl.col('date').str.to_date('%Y-%m-%d')).collect()
df_msft = pl.scan_csv('/mnt/windows/windows_hanka_bcthesis/full_stock_prices/MSFT.csv').with_columns(pl.col('date').str.to_date('%Y-%m-%d')).collect()
df_googl = pl.scan_csv('/mnt/windows/windows_hanka_bcthesis/full_stock_prices/GOOGL.csv').with_columns(pl.col('date').str.to_date('%Y-%m-%d')).collect()
df_amzn = pl.scan_csv('/mnt/windows/windows_hanka_bcthesis/full_stock_prices/AMZN.csv').with_columns(pl.col('date').str.to_date('%Y-%m-%d')).collect()
df_nvda = pl.scan_csv('/mnt/windows/windows_hanka_bcthesis/full_stock_prices/NVDA.csv').with_columns(pl.col('date').str.to_date('%Y-%m-%d')).collect() # Or FB.csv

# Package them up
dict_of_dfs = {
    "AAPL": df_aapl.select(['date', 'close']),
    "MSFT": df_msft.select(['date', 'close']),
    "GOOGL": df_googl.select(['date', 'close']),
    "AMZN": df_amzn.select(['date', 'close']),
    "NVDA": df_nvda.select(['date', 'close'])
}

df_tfidf = (
    pl.scan_parquet('/mnt/windows/windows_hanka_bcthesis/full_news/tfidf_nasdaq.parquet')
    # Use whatever the date column is actually called in this file
    .filter(pl.col("trading_session_date_utc").is_between(pl.date(2006, 10, 20), pl.date(2026 , 12, 31)))
    .collect()
)

df_sent = (
    pl.scan_parquet('/mnt/red/red_hanka_bcthesis/full_news/finbert_nasdaq_2006-2023_avg_sentiment.parquet')
    # Use whatever the date column is actually called in this file
    .filter(pl.col("trading_session_date_utc").is_between(pl.date(2006, 10, 20), pl.date(2026, 12, 31)))
    .collect()
)

In [4]:
ml_object = mach_lern(test_size=0.3)

In [5]:
ml_object.load_and_prepare_multiple_price_data(dict_of_dfs, start_date=date(2006, 10, 20), end_date=date(2026, 12, 31)) 
ml_object.load_tfidf_data(df_tfidf)
final_df = ml_object.load_finbert_data(df_sent)
final_df

Loading prices for multiple stocks: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA']...
Master multi-stock timeline established. Shape: (20653, 9)
Loading TF-IDF data and aligning with timeline...
TF-IDF aligned. Total columns in master: 5009
Loading FinBERT data and aligning with timeline...
FinBERT aligned. Total columns in master: 5013

shape: (21_937, 5_013)
┌─────────────────┬────────────────┬─────────────┬─────────────┬───┬───────┬──────┬────────┬───────┐
│ trading_date_ut ┆ target_next_da ┆ nyse_ticker ┆ return_lag0 ┆ … ┆ zloti ┆ zone ┆ zumiez ┆ zynga │
│ c               ┆ y              ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---  ┆ ---    ┆ ---   │
│ ---             ┆ ---            ┆ str         ┆ f64         ┆   ┆ f64   ┆ f64  ┆ f64    ┆ f64   │
│ date            ┆ i8             ┆             ┆             ┆   ┆       ┆      ┆        ┆       │
╞═════════════════╪════════════════╪═════════════╪═════════════╪═══╪═══════╪══════╪════════╪═══════╡
│ 2006-10-30      ┆ 1              ┆ AAPL        ┆ 0.000124    ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2006-10-30      ┆ 1              ┆ MSFT        ┆ 0.006704    ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2006-10-30      ┆ 0              ┆ GOOGL       ┆ 0.002883    ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2006-10-30      ┆ 0              ┆ AMZN        ┆ -0.002354   ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2006-10-30      ┆ 1              ┆ NVDA        ┆ 0.012044    ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ …               ┆ …              ┆ …           ┆ …           ┆ … ┆ …     ┆ …    ┆ …      ┆ …     │
│ 2023-12-26      ┆ 1              ┆ NVDA        ┆ 0.009195    ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2023-12-27      ┆ 1              ┆ AAPL        ┆ 0.000518    ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2023-12-27      ┆ 1              ┆ MSFT        ┆ -0.001575   ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2023-12-27      ┆ 1              ┆ AMZN        ┆ -0.000456   ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
│ 2023-12-27      ┆ 1              ┆ NVDA        ┆ 0.0028      ┆ … ┆ 0.0   ┆ 0.0  ┆ 0.0    ┆ 0.0   │
└─────────────────┴────────────────┴─────────────┴─────────────┴───┴───────┴──────┴────────┴───────┘

In [6]:
# Start the engine manually. 
# It will print the dashboard link ONE time, and that link will stay valid.
ml_object.start_dask_cluster()

Booting up LocalCUDACluster...

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)

Dask dashboard available at: http://127.0.0.1:8787/status

In [ ]:
try:
    with open("optimal_parameters.jsonl", "r") as f:
        lines = f.readlines()

    # filter for LR entries
    filtered_entries = []
    for line in lines:
        entry = json.loads(line)
        if entry.get("model_type") == "LR":
            ts = datetime.strptime(entry["timestamp"], "%Y-%m-%d %H:%M:%S")
            if ts >= datetime(2026, 3, 10, 21, 0, 0) and ts <= datetime(2026, 3, 10, 23, 59, 59):
                filtered_entries.append(entry)

    # evaluate each set of parameters
    nmb = 1
    for entry in filtered_entries:
        mode = entry["mode"]
        param_grid = entry["hyperparameters"]
        param_grid = {k: [v] for k, v in param_grid.items()}
        acc = entry["best_cv_accuracy"]
        auc = entry["best_cv_auc"]
        print(f"\n{nmb }. Evaluating LR mode: {mode} with params: {param_grid}")
        print(f"\nTrain accuracy {acc} and AUC: {auc}")

        best_pipeline, x_test, y_test, active_features = ml_object.train_logistic_regression(mode=mode, param_grid=param_grid)
        y_pred, y_probs = ml_object.evaluate(
            mode=mode, 
            best_pipeline=best_pipeline, 
            x_test=x_test, 
            y_test=y_test, 
            active_features=active_features
        )
        nmb += 1
finally:
    ml_object.stop_dask_cluster()

1. Evaluating LR mode: price with params: {'logr__C': [0.01], 'logr__class_weight': [None], 'logr__l1_ratio': [1.0], 'logr__tol': [0.0001]}

Train accuracy 0.5102 and AUC: 0.5024

Starting Experiment: PRICE (6 features)

--- Running GPU GridSearchCV (5 splits) ---
[2026-03-11 19:04:15.986] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
[2026-03-11 19:04:16.099] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
Calculating CV AUC for best model...
Best Params: {'logr__C': 0.01, 'logr__class_weight': None, 'logr__l1_ratio': 1.0, 'logr__tol': 0.0001}
Best CV Accuracy: 0.5102 | Best CV AUC: 0.5024
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.4785, Max Prob: 0.5259, Mean Prob: 0.5075
Final Test Accuracy: 0.5406
Final Test ROC AUC: 0.5233

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.45      0.00      0.00      2459
      Up (1)       0.54      1.00      0.70      2896

    accuracy                           0.54      5355
   macro avg       0.50      0.50      0.35      5355
weighted avg       0.50      0.54      0.38      5355


--- Weight/Importance Analysis ---
Metric: Linear Coefficients (Magnitude = Impact, Sign = Direction)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.001565
Most influential feature: 'return_lag0' (Importance: -0.0094)

Confusion Matrix:
[[   5 2454]
 [   6 2890]]

2. Evaluating LR mode: tfidf with params: {'logr__C': [0.3], 'logr__class_weight': [None], 'logr__l1_ratio': [0.8], 'logr__tol': [0.0001]}

Train accuracy 0.5034 and AUC: 0.4956

Starting Experiment: TFIDF (5000 features)

--- Running GPU GridSearchCV (5 splits) ---

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.28 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(

[2026-03-11 19:04:40.481] [CUML] [warning] QWL-QN: max iterations reached
[2026-03-11 19:04:40.482] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.28 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(

[2026-03-11 19:05:09.782] [CUML] [warning] QWL-QN: max iterations reached
[2026-03-11 19:05:09.782] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
Calculating CV AUC for best model...
[2026-03-11 19:05:38.529] [CUML] [warning] QWL-QN: max iterations reached
[2026-03-11 19:05:38.530] [CUML] [warning] Maximum iterations reached before solver is converged. To increase model accuracy you can increase the number of iterations (max_iter) or improve the scaling of the input data.
Best Params: {'logr__C': 0.3, 'logr__class_weight': None, 'logr__l1_ratio': 0.8, 'logr__tol': 0.0001}
Best CV Accuracy: 0.5025 | Best CV AUC: 0.4957
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.0000, Max Prob: 1.0000, Mean Prob: 0.4328
Final Test Accuracy: 0.4926
Final Test ROC AUC: 0.5025

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.46      0.57      0.51      2459
      Up (1)       0.54      0.43      0.48      2896

    accuracy                           0.49      5355
   macro avg       0.50      0.50      0.49      5355
weighted avg       0.50      0.49      0.49      5355


--- Weight/Importance Analysis ---
Metric: Linear Coefficients (Magnitude = Impact, Sign = Direction)
--- Weight Analysis ---
Price Features: [None in this mode]
Average Absolute TF-IDF Importance (5000 features): 0.022427
Most influential feature: 'rumor' (Importance: 0.2740)

Confusion Matrix:
[[1391 1068]
 [1649 1247]]

3. Evaluating LR mode: finbert with params: {'logr__C': [0.03], 'logr__class_weight': [None], 'logr__l1_ratio': [1.0], 'logr__tol': [0.0001]}

Train accuracy 0.5106 and AUC: 0.4915

Starting Experiment: FINBERT (4 features)

--- Running GPU GridSearchCV (5 splits) ---
Calculating CV AUC for best model...
Best Params: {'logr__C': 0.03, 'logr__class_weight': None, 'logr__l1_ratio': 1.0, 'logr__tol': 0.0001}
Best CV Accuracy: 0.5106 | Best CV AUC: 0.4915
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.5038, Max Prob: 0.5091, Mean Prob: 0.5069
Final Test Accuracy: 0.5408
Final Test ROC AUC: 0.5024

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.00      0.00      0.00      2459
      Up (1)       0.54      1.00      0.70      2896

    accuracy                           0.54      5355
   macro avg       0.27      0.50      0.35      5355
weighted avg       0.29      0.54      0.38      5355


--- Weight/Importance Analysis ---
Metric: Linear Coefficients (Magnitude = Impact, Sign = Direction)
--- Weight Analysis ---
Price Features: [None in this mode]
Average Absolute FinBERT Importance (4 features): 0.002855
Most influential feature: 'avg_neu' (Importance: 0.0074)

Confusion Matrix:
[[   0 2459]
 [   0 2896]]

4. Evaluating LR mode: hybrid_tfidf with params: {'logr__C': [0.01], 'logr__class_weight': ['balanced'], 'logr__l1_ratio': [0.0], 'logr__tol': [0.001]}

Train accuracy 0.5054 and AUC: 0.5004

Starting Experiment: HYBRID_TFIDF (5006 features)

--- Running GPU GridSearchCV (5 splits) ---

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.85 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.85 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(

Calculating CV AUC for best model...
Best Params: {'logr__C': 0.01, 'logr__class_weight': 'balanced', 'logr__l1_ratio': 0.0, 'logr__tol': 0.001}
Best CV Accuracy: 0.5054 | Best CV AUC: 0.5004
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.0000, Max Prob: 1.0000, Mean Prob: 0.6662
Final Test Accuracy: 0.5104
Final Test ROC AUC: 0.5039

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.45      0.33      0.38      2459
      Up (1)       0.54      0.66      0.59      2896

    accuracy                           0.51      5355
   macro avg       0.50      0.50      0.49      5355
weighted avg       0.50      0.51      0.50      5355


--- Weight/Importance Analysis ---
Metric: Linear Coefficients (Magnitude = Impact, Sign = Direction)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.030246
Average Absolute TF-IDF Importance (5000 features): 0.024186
Most influential feature: 'rumor' (Importance: 0.1183)

Confusion Matrix:
[[ 814 1645]
 [ 977 1919]]

5. Evaluating LR mode: hybrid_finbert with params: {'logr__C': [0.01], 'logr__class_weight': [None], 'logr__l1_ratio': [1.0], 'logr__tol': [0.0001]}

Train accuracy 0.5102 and AUC: 0.5024

Starting Experiment: HYBRID_FINBERT (10 features)

--- Running GPU GridSearchCV (5 splits) ---
[2026-03-11 19:06:38.898] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
Calculating CV AUC for best model...
Best Params: {'logr__C': 0.01, 'logr__class_weight': None, 'logr__l1_ratio': 1.0, 'logr__tol': 0.0001}
Best CV Accuracy: 0.5102 | Best CV AUC: 0.5024
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.4785, Max Prob: 0.5259, Mean Prob: 0.5075
Final Test Accuracy: 0.5406
Final Test ROC AUC: 0.5233

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.45      0.00      0.00      2459
      Up (1)       0.54      1.00      0.70      2896

    accuracy                           0.54      5355
   macro avg       0.50      0.50      0.35      5355
weighted avg       0.50      0.54      0.38      5355


--- Weight/Importance Analysis ---
Metric: Linear Coefficients (Magnitude = Impact, Sign = Direction)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.001565
Average Absolute FinBERT Importance (4 features): 0.000000
Most influential feature: 'return_lag0' (Importance: -0.0094)

Confusion Matrix:
[[   5 2454]
 [   6 2890]]
Shutting down Dask cluster and freeing ports...
Cluster successfully shut down.

**Random Forest**

In [ ]:
#Evaluate 1st try best RF parameters on test data
with open("optimal_parameters.jsonl", "r") as f:
    lines = f.readlines()

# filter for RF entries
filtered_entries = []
for line in lines:
    entry = json.loads(line)
    if entry.get("model_type") == "RF":
        ts = datetime.strptime(entry["timestamp"], "%Y-%m-%d %H:%M:%S")
        if ts >= datetime(2026, 3, 10, 21, 0, 0) and ts <= datetime(2026, 3, 11, 1, 59, 59):
            filtered_entries.append(entry)

# evaluate each set of parameters
nmb = 1
for entry in filtered_entries:
    mode = entry["mode"]
    param_grid = entry["hyperparameters"]
    param_grid = {k: [v] for k, v in param_grid.items()}
    acc = entry["best_cv_accuracy"]
    auc = entry["best_cv_auc"]
    print(f"\n{nmb }. Evaluating RF mode: {mode} with params: {param_grid}")
    print(f"\nTrain accuracy {acc} and AUC: {auc}")

    best_pipeline, x_test, y_test, active_features = ml_object.train_random_forest(mode=mode, param_grid=param_grid)
    y_pred, y_probs = ml_object.evaluate(
        mode=mode, 
        best_pipeline=best_pipeline, 
        x_test=x_test, 
        y_test=y_test, 
        active_features=active_features
    )
    nmb += 1

1. Evaluating RF mode: price with params: {'rf__max_depth': [14], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [400]}

Train accuracy 0.5071 and AUC: 0.5008

Starting Experiment: RF PRICE (6 features)

--- Running GPU GridSearchCV (5 splits) ---
Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 14, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 400}
Best CV Accuracy: 0.5071 | Best CV AUC: 0.5008
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.2261, Max Prob: 0.6744, Mean Prob: 0.5099
Final Test Accuracy: 0.5154
Final Test ROC AUC: 0.5154

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.47      0.40      0.43      2459
      Up (1)       0.55      0.61      0.58      2896

    accuracy                           0.52      5355
   macro avg       0.51      0.51      0.51      5355
weighted avg       0.51      0.52      0.51      5355


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.166667
Most influential feature: 'return_lag0' (Importance: 0.1749)

Confusion Matrix:
[[ 994 1465]
 [1130 1766]]

2. Evaluating RF mode: tfidf with params: {'rf__max_depth': [6], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [200]}

Train accuracy 0.5159 and AUC: 0.4995

Starting Experiment: RF TFIDF (5000 features)

--- Running GPU GridSearchCV (5 splits) ---

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.28 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.28 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(

Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 6, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 200}
Best CV Accuracy: 0.5159 | Best CV AUC: 0.4995
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.4534, Max Prob: 0.5433, Mean Prob: 0.4995
Final Test Accuracy: 0.5154
Final Test ROC AUC: 0.5112

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.47      0.52      0.50      2459
      Up (1)       0.56      0.51      0.53      2896

    accuracy                           0.52      5355
   macro avg       0.52      0.52      0.51      5355
weighted avg       0.52      0.52      0.52      5355


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Price Features: [None in this mode]
Average Absolute TF-IDF Importance (5000 features): 0.000200
Most influential feature: 'primari' (Importance: 0.0019)

Confusion Matrix:
[[1277 1182]
 [1413 1483]]

3. Evaluating RF mode: finbert with params: {'rf__max_depth': [14], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [5], 'rf__n_estimators': [400]}

Train accuracy 0.5051 and AUC: 0.4975

Starting Experiment: RF FINBERT (4 features)

--- Running GPU GridSearchCV (5 splits) ---
Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 14, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 5, 'rf__n_estimators': 400}
Best CV Accuracy: 0.5051 | Best CV AUC: 0.4975
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.2177, Max Prob: 0.7597, Mean Prob: 0.4515
Final Test Accuracy: 0.4781
Final Test ROC AUC: 0.4973

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.46      0.77      0.58      2459
      Up (1)       0.54      0.23      0.32      2896

    accuracy                           0.48      5355
   macro avg       0.50      0.50      0.45      5355
weighted avg       0.50      0.48      0.44      5355


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Price Features: [None in this mode]
Average Absolute FinBERT Importance (4 features): 0.250000
Most influential feature: 'avg_pos' (Importance: 0.2575)

Confusion Matrix:
[[1902  557]
 [2238  658]]

4. Evaluating RF mode: hybrid_tfidf with params: {'rf__max_depth': [6], 'rf__max_features': ['log2'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [200]}

Train accuracy 0.5128 and AUC: 0.5106

Starting Experiment: RF HYBRID_TFIDF (5006 features)

--- Running GPU GridSearchCV (5 splits) ---

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.85 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 477.85 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(

Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 6, 'rf__max_features': 'log2', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 200}
Best CV Accuracy: 0.5128 | Best CV AUC: 0.5106
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.4659, Max Prob: 0.5363, Mean Prob: 0.5018
Final Test Accuracy: 0.5156
Final Test ROC AUC: 0.5047

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.47      0.42      0.45      2459
      Up (1)       0.55      0.59      0.57      2896

    accuracy                           0.52      5355
   macro avg       0.51      0.51      0.51      5355
weighted avg       0.51      0.52      0.51      5355


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.000191
Average Absolute TF-IDF Importance (5000 features): 0.000200
Most influential feature: 'cooper' (Importance: 0.0018)

Confusion Matrix:
[[1040 1419]
 [1175 1721]]

5. Evaluating RF mode: hybrid_finbert with params: {'rf__max_depth': [14], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [400]}

Train accuracy 0.5023 and AUC: 0.4931

Starting Experiment: RF HYBRID_FINBERT (10 features)

--- Running GPU GridSearchCV (5 splits) ---
Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 14, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 400}
Best CV Accuracy: 0.5023 | Best CV AUC: 0.4931
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.2702, Max Prob: 0.6477, Mean Prob: 0.4816
Final Test Accuracy: 0.4911
Final Test ROC AUC: 0.5046

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.46      0.71      0.56      2459
      Up (1)       0.55      0.31      0.39      2896

    accuracy                           0.49      5355
   macro avg       0.51      0.51      0.48      5355
weighted avg       0.51      0.49      0.47      5355


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.098809
Average Absolute FinBERT Importance (4 features): 0.101786
Most influential feature: 'daily_article_count' (Importance: 0.1091)

Confusion Matrix:
[[1744  715]
 [2010  886]]

In [7]:
#Evaluate 2nd try best RF parameters on test data
with open("optimal_parameters.jsonl", "r") as f:
    lines = f.readlines()

# filter for RF entries
filtered_entries = []
for line in lines:
    entry = json.loads(line)
    if entry.get("model_type") == "RF":
        ts = datetime.strptime(entry["timestamp"], "%Y-%m-%d %H:%M:%S")
        if ts >= datetime(2026, 3, 26, 13, 0, 0) and ts <= datetime(2026, 3, 26, 13, 59, 59):
            filtered_entries.append(entry)

# evaluate each set of parameters
nmb = 1
for entry in filtered_entries:
    mode = entry["mode"]
    param_grid = entry["hyperparameters"]
    param_grid = {k: [v] for k, v in param_grid.items()}
    acc = entry["best_cv_accuracy"]
    auc = entry["best_cv_auc"]
    print(f"\n{nmb }. Evaluating RF mode: {mode} with params: {param_grid}")
    print(f"\nTrain accuracy {acc} and AUC: {auc}")

    best_pipeline, x_test, y_test, active_features = ml_object.train_random_forest(mode=mode, param_grid=param_grid)
    y_pred, y_probs = ml_object.evaluate(
        mode=mode, 
        best_pipeline=best_pipeline, 
        x_test=x_test, 
        y_test=y_test, 
        active_features=active_features
    )
    nmb += 1

1. Evaluating RF mode: price with params: {'rf__max_depth': [6], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [200]}

Train accuracy 0.5142 and AUC: 0.5068

Starting Experiment: RF PRICE (6 features)
Booting up LocalCUDACluster...

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/node.py:187: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 41805 instead
  warnings.warn(
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)

Dask dashboard available at: http://127.0.0.1:41805/status

--- Running GPU GridSearchCV (10 splits) ---
Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 6, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 200}
Best CV Accuracy: 0.5142 | Best CV AUC: 0.5068
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.3119, Max Prob: 0.6282, Mean Prob: 0.5099
Final Test Accuracy: 0.5193
Final Test ROC AUC: 0.5028

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.48      0.29      0.36      3075
      Up (1)       0.54      0.72      0.62      3507

    accuracy                           0.52      6582
   macro avg       0.51      0.50      0.49      6582
weighted avg       0.51      0.52      0.49      6582


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.166667
Most influential feature: 'return_lag1' (Importance: 0.1882)

Confusion Matrix:
[[ 877 2198]
 [ 966 2541]]

2. Evaluating RF mode: tfidf with params: {'rf__max_depth': [6], 'rf__max_features': ['log2'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [400]}

Train accuracy 0.5072 and AUC: 0.5111

Starting Experiment: RF TFIDF (5000 features)

--- Running GPU GridSearchCV (10 splits) ---

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 586.39 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
terminate called after throwing an instance of 'rmm::out_of_memory'
  what():  std::bad_alloc: out_of_memory: CUDA error (failed to allocate 42649088 bytes) at: /home/sj5/.micromamba/envs/thesis_ml/include/rmm/mr/cuda_memory_resource.hpp
2026-04-16 21:18:26,931 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:36149' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'cv-split-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 6), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 2), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 5), ('randomforestclassifier-fit-467b68ef153030dcad30f81d5a1df0ca', 0, 1), 'randomforestclassifier-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 8), '_indexable-bba9c18f273f26abd2f4b299720b6b6b', 'DataFrame-8e87a92f-87e0-4ffe-af0b-0c0009aa399e', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 7), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 0), 'cv-n-samples-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 3), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 9)} (stimulus_id='handle-worker-cleanup-1776367106.9314466')
2026-04-16 21:18:27,018 - distributed.nanny - WARNING - Restarting worker
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)
terminate called after throwing an instance of 'rmm::out_of_memory'
  what():  std::bad_alloc: out_of_memory: CUDA error (failed to allocate 42649088 bytes) at: /home/sj5/.micromamba/envs/thesis_ml/include/rmm/mr/cuda_memory_resource.hpp
2026-04-16 21:18:54,348 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:39453' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'cv-split-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 6), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 2), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 5), ('randomforestclassifier-fit-467b68ef153030dcad30f81d5a1df0ca', 0, 1), 'randomforestclassifier-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 8), '_indexable-bba9c18f273f26abd2f4b299720b6b6b', 'DataFrame-8e87a92f-87e0-4ffe-af0b-0c0009aa399e', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 7), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 0), 'cv-n-samples-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 3), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 9)} (stimulus_id='handle-worker-cleanup-1776367134.3484583')
2026-04-16 21:18:54,434 - distributed.nanny - WARNING - Restarting worker
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)
terminate called after throwing an instance of 'rmm::out_of_memory'
  what():  std::bad_alloc: out_of_memory: CUDA error (failed to allocate 42649088 bytes) at: /home/sj5/.micromamba/envs/thesis_ml/include/rmm/mr/cuda_memory_resource.hpp
2026-04-16 21:19:21,696 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:39303' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'cv-split-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 6), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 2), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 5), ('randomforestclassifier-fit-467b68ef153030dcad30f81d5a1df0ca', 0, 1), 'randomforestclassifier-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 8), '_indexable-bba9c18f273f26abd2f4b299720b6b6b', 'DataFrame-8e87a92f-87e0-4ffe-af0b-0c0009aa399e', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 7), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 0), 'cv-n-samples-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 3), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 9)} (stimulus_id='handle-worker-cleanup-1776367161.6958663')
2026-04-16 21:19:21,780 - distributed.nanny - WARNING - Restarting worker
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)
terminate called after throwing an instance of 'rmm::out_of_memory'
  what():  std::bad_alloc: out_of_memory: CUDA error (failed to allocate 42649088 bytes) at: /home/sj5/.micromamba/envs/thesis_ml/include/rmm/mr/cuda_memory_resource.hpp
2026-04-16 21:19:48,959 - distributed.scheduler - ERROR - Task ('randomforestclassifier-fit-467b68ef153030dcad30f81d5a1df0ca', 0, 4) marked as failed because 4 workers died while trying to run it
2026-04-16 21:19:48,959 - distributed.scheduler - ERROR - Task ('pipeline-467b68ef153030dcad30f81d5a1df0ca', 0, 1) marked as failed because 4 workers died while trying to run it
2026-04-16 21:19:48,960 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:42257' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'cv-split-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 6), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 2), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 5), ('randomforestclassifier-fit-467b68ef153030dcad30f81d5a1df0ca', 0, 1), 'randomforestclassifier-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 8), '_indexable-bba9c18f273f26abd2f4b299720b6b6b', 'DataFrame-8e87a92f-87e0-4ffe-af0b-0c0009aa399e', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 7), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 0), 'cv-n-samples-467b68ef153030dcad30f81d5a1df0ca', ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 3), ('score-467b68ef153030dcad30f81d5a1df0ca', 0, 9)} (stimulus_id='handle-worker-cleanup-1776367188.9587348')
('score-467b68ef153030dcad30f81d5a1df0ca', 0, 1) has failed... retrying
2026-04-16 21:19:49,048 - distributed.nanny - WARNING - Restarting worker
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/rapids_dask_dependency/dask_loader.py:36: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  return importlib.import_module(spec.name)

KeyError: ('pipeline-467b68ef153030dcad30f81d5a1df0ca', 0, 1)

In [ ]:
#Evaluate 2nd.2 try best RF parameters on test data for
with open("optimal_parameters.jsonl", "r") as f:
    lines = f.readlines()

# filter for RF entries
filtered_entries = []
for line in lines:
    entry = json.loads(line)
    if entry.get("model_type") == "RF":
        ts = datetime.strptime(entry["timestamp"], "%Y-%m-%d %H:%M:%S")
        if ts >= datetime(2026, 3, 26, 13, 0, 0) and ts <= datetime(2026, 3, 26, 13, 59, 59):
            filtered_entries.append(entry)

# evaluate each set of parameters
nmb = 1
for entry in filtered_entries:
    mode = entry["mode"]
    param_grid = entry["hyperparameters"]
    param_grid = {k: [v] for k, v in param_grid.items()}
    acc = entry["best_cv_accuracy"]
    auc = entry["best_cv_auc"]
    print(f"\n{nmb }. Evaluating RF mode: {mode} with params: {param_grid}")
    print(f"\nTrain accuracy {acc} and AUC: {auc}")

    best_pipeline, x_test, y_test, active_features = ml_object.train_random_forest(mode=mode, param_grid=param_grid)
    y_pred, y_probs = ml_object.evaluate(
        mode=mode, 
        best_pipeline=best_pipeline, 
        x_test=x_test, 
        y_test=y_test, 
        active_features=active_features
    )
    nmb += 1

1. Evaluating RF mode: price with params: {'rf__max_depth': [6], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [200]}

Train accuracy 0.5142 and AUC: 0.5068

Starting Experiment: RF PRICE (6 features)

--- Running GPU GridSearchCV (10 splits) ---
Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 6, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 200}
Best CV Accuracy: 0.5142 | Best CV AUC: 0.5068
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.3119, Max Prob: 0.6282, Mean Prob: 0.5099
Final Test Accuracy: 0.5193
Final Test ROC AUC: 0.5028

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.48      0.29      0.36      3075
      Up (1)       0.54      0.72      0.62      3507

    accuracy                           0.52      6582
   macro avg       0.51      0.50      0.49      6582
weighted avg       0.51      0.52      0.49      6582


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.166667
Most influential feature: 'return_lag1' (Importance: 0.1882)

Confusion Matrix:
[[ 877 2198]
 [ 966 2541]]

2. Evaluating RF mode: tfidf with params: {'rf__max_depth': [6], 'rf__max_features': ['log2'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [400]}

Train accuracy 0.5072 and AUC: 0.5111

Starting Experiment: RF TFIDF (5000 features)

--- Running GPU GridSearchCV (10 splits) ---

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 586.39 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 586.39 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(

Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 6, 'rf__max_features': 'log2', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 400}
Best CV Accuracy: 0.5072 | Best CV AUC: 0.5111
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.4934, Max Prob: 0.5360, Mean Prob: 0.5146
Final Test Accuracy: 0.5304
Final Test ROC AUC: 0.4863

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.44      0.02      0.04      3075
      Up (1)       0.53      0.98      0.69      3507

    accuracy                           0.53      6582
   macro avg       0.49      0.50      0.36      6582
weighted avg       0.49      0.53      0.39      6582


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Price Features: [None in this mode]
Average Absolute TF-IDF Importance (5000 features): 0.000200
Most influential feature: 'pure' (Importance: 0.0010)

Confusion Matrix:
[[  64 3011]
 [  80 3427]]

3. Evaluating RF mode: finbert with params: {'rf__max_depth': [10], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [200]}

Train accuracy 0.4922 and AUC: 0.5026

Starting Experiment: RF FINBERT (4 features)

--- Running GPU GridSearchCV (10 splits) ---
Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 10, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 200}
Best CV Accuracy: 0.4922 | Best CV AUC: 0.5026
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.2998, Max Prob: 0.7319, Mean Prob: 0.4830
Final Test Accuracy: 0.4765
Final Test ROC AUC: 0.4872

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.46      0.67      0.54      3075
      Up (1)       0.51      0.31      0.38      3507

    accuracy                           0.48      6582
   macro avg       0.49      0.49      0.46      6582
weighted avg       0.49      0.48      0.46      6582


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Price Features: [None in this mode]
Average Absolute FinBERT Importance (4 features): 0.250000
Most influential feature: 'avg_neg' (Importance: 0.2548)

Confusion Matrix:
[[2062 1013]
 [2433 1074]]

4. Evaluating RF mode: hybrid_tfidf with params: {'rf__max_depth': [10], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [5], 'rf__n_estimators': [400]}

Train accuracy 0.5031 and AUC: 0.5138

Starting Experiment: RF HYBRID_TFIDF (5006 features)

--- Running GPU GridSearchCV (10 splits) ---

/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 587.10 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
/home/sj5/.micromamba/envs/thesis_ml/lib/python3.10/site-packages/distributed/client.py:3370: UserWarning: Sending large graph of size 587.09 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(

Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 10, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 5, 'rf__n_estimators': 400}
Best CV Accuracy: 0.5031 | Best CV AUC: 0.5138
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.4692, Max Prob: 0.5609, Mean Prob: 0.5165
Final Test Accuracy: 0.5248
Final Test ROC AUC: 0.5021

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.47      0.13      0.21      3075
      Up (1)       0.53      0.87      0.66      3507

    accuracy                           0.52      6582
   macro avg       0.50      0.50      0.43      6582
weighted avg       0.50      0.52      0.45      6582


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.001601
Average Absolute TF-IDF Importance (5000 features): 0.000198
Most influential feature: 'return_lag5' (Importance: 0.0018)

Confusion Matrix:
[[ 408 2667]
 [ 461 3046]]

5. Evaluating RF mode: hybrid_finbert with params: {'rf__max_depth': [6], 'rf__max_features': ['sqrt'], 'rf__min_samples_leaf': [10], 'rf__n_estimators': [200]}

Train accuracy 0.4965 and AUC: 0.498

Starting Experiment: RF HYBRID_FINBERT (10 features)

--- Running GPU GridSearchCV (10 splits) ---
Calculating CV AUC for best model...
Best Params: {'rf__max_depth': 6, 'rf__max_features': 'sqrt', 'rf__min_samples_leaf': 10, 'rf__n_estimators': 200}
Best CV Accuracy: 0.4965 | Best CV AUC: 0.4980
Optimal parameters saved to optimal_parameters.jsonl

--- Final Model Reality Check (Untouched Test Set) ---
Min Prob: 0.3677, Max Prob: 0.5929, Mean Prob: 0.5050
Final Test Accuracy: 0.5052
Final Test ROC AUC: 0.4996

Classification Report:
              precision    recall  f1-score   support

    Down (0)       0.47      0.39      0.43      3075
      Up (1)       0.53      0.60      0.56      3507

    accuracy                           0.51      6582
   macro avg       0.50      0.50      0.50      6582
weighted avg       0.50      0.51      0.50      6582


--- Weight/Importance Analysis ---
Metric: Gini Importance (Magnitude = How often it was useful)
--- Weight Analysis ---
Average Absolute Price Weight (6 features): 0.092289
Average Absolute FinBERT Importance (4 features): 0.111566
Most influential feature: 'avg_neg' (Importance: 0.1352)

Confusion Matrix:
[[1210 1865]
 [1392 2115]]

In [ ]:
#print the results + hyperparameters used for 26.3. run of RF
with open("optimal_parameters.jsonl", "r") as f:
    lines = f.readlines()

# filter for RF entries
filtered_entries = []
for line in lines:
    entry = json.loads(line)
    if entry.get("model_type") == "RF":
        ts = datetime.strptime(entry["timestamp"], "%Y-%m-%d %H:%M:%S")
        if ts >= datetime(2026, 3, 26, 13, 0, 0) and ts <= datetime(2026, 3, 26, 13, 59, 59):
            filtered_entries.append(entry)

flat_entries = []
for entry in filtered_entries:
    # Explicitly pick only the base columns you want
    flat_entry = {
        "timestamp": entry.get("timestamp"),
        "mode": entry.get("mode"),
        "best_cv_accuracy": entry.get("best_cv_accuracy"),
    }
    
    # Expand hyperparameters directly into the dictionary, which creates new columns
    hp = entry.get("hyperparameters", {})
    if isinstance(hp, dict):
        flat_entry.update(hp)
        
    flat_entries.append(flat_entry)

# Convert to Polars DataFrame
rf_df = pl.from_dicts(flat_entries) if flat_entries else pl.DataFrame()

display(rf_df)

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ timestamp    ┆ mode        ┆ best_cv_acc ┆ rf__max_dep ┆ rf__max_fea ┆ rf__min_sam ┆ rf__n_estim │
│ ---          ┆ ---         ┆ uracy       ┆ th          ┆ tures       ┆ ples_leaf   ┆ ators       │
│ str          ┆ str         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆             ┆ f64         ┆ i64         ┆ str         ┆ i64         ┆ i64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2026-03-26   ┆ price       ┆ 0.5142      ┆ 6           ┆ sqrt        ┆ 10          ┆ 200         │
│ 13:13:25     ┆             ┆             ┆             ┆             ┆             ┆             │
│ 2026-03-26   ┆ tfidf       ┆ 0.5072      ┆ 6           ┆ log2        ┆ 10          ┆ 400         │
│ 13:19:48     ┆             ┆             ┆             ┆             ┆             ┆             │
│ 2026-03-26   ┆ finbert     ┆ 0.4922      ┆ 10          ┆ sqrt        ┆ 10          ┆ 200         │
│ 13:22:15     ┆             ┆             ┆             ┆             ┆             ┆             │
│ 2026-03-26   ┆ hybrid_tfid ┆ 0.5031      ┆ 10          ┆ sqrt        ┆ 5           ┆ 400         │
│ 13:28:41     ┆ f           ┆             ┆             ┆             ┆             ┆             │
│ 2026-03-26   ┆ hybrid_finb ┆ 0.4965      ┆ 6           ┆ sqrt        ┆ 10          ┆ 200         │
│ 13:31:13     ┆ ert         ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
ml_object.stop_dask_cluster()

No active cluster to shut down.